apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hello-world-nginx
  annotations:
    github.com/project-slug: ducthanh1809/hello-world-nginx
spec:
  type: other
  lifecycle: unknown
  owner: guests
