kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/instance: ${{ values.repoName }}
    app.kubernetes.io/name: ${{ values.repoName }}
    app.kubernetes.io/part-of: ${{ values.repoName }}-app
    app.kubernetes.io/managed-by: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${{ values.repoName }}
  template:
    metadata:
      labels:
        app: ${{ values.repoName }}
        app.kubernetes.io/version: v1.0
        app.kubernetes.io/instance: ${{ values.repoName }}
        app.kubernetes.io/name: ${{ values.repoName }}
        app.kubernetes.io/part-of: ${{ values.repoName }}-app
        app.kubernetes.io/managed-by: backstage
        backstage.io/kubernetes-id: ${{ values.namespace }}
    spec:
      containers:
        - name: ${{ values.repoName }}
          image: ${{ values.imageRepository }}/${{ values.imageUrl }}/${{ values.repoName }}:latest
          ports:
            - name: http-${{ values.port }}
              containerPort: ${{ values.port }}
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
