kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: ${{ values.repoName }}
  namespace: ${{ values.namespace }}
  labels:
    app: ${{ values.repoName }}
    app.kubernetes.io/version: v1.0
    app.kubernetes.io/instance: ${{ values.repoName }}
    app.kubernetes.io/name: ${{ values.repoName }}
    app.kubernetes.io/part-of: ${{ values.repoName }}-app
    app.kubernetes.io/managed-by: backstage
    backstage.io/kubernetes-id: ${{ values.namespace }}
spec:
  host: ${{ values.hostUrl }}
  to:
    kind: Service
    name: ${{ values.repoName }}
    weight: 100
  port:
    targetPort: ${{ values.port }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
